### ISSUE TITLE
'Card' is not defined when executing onclick from Entity

### ISSUE THREAD

**Issue by Morzat95** [agusalex/museoAR#24]
{
    "name": "Levanta Mano",
    "description": "Levantá la mano izquierda frente al espejo plano. Después tocá el botón.",
    "cards": [
        {
            "id": "Manos",
            "description": "Tu reflejo/imagen en el espejo, ¿qué mano levanta?",
            "objects": [
                {
                    "id": "BtnDer",
                    "position": "1.232 0.16617 0.09778",
                    "rotation": "0 0 0",
                    "scale": "1 1 1",
                    "type": "a-box",
                    "onclick": "goTo(TarjInvers)",
                    "color": "green",
                    "marker": "hiro"
                },
                {
                    "id": "BtnIzq",
                    "position": "0 0 0",
                    "rotation": "0 0 0",
                    "scale": "1 1 1",
                    "type": "a-box",
                    "onclick": "goTo(Retry)",
                    "color": "red",
                    "marker": "hiro"
                }
            ]
        },
        {
            "id": "Retry",
            "description": "Volvé a intentarlo.",
            "next": 5,
            "type": "redirect",
            "value": "http://proyectar-alt.herokuapp.com/es/activity/5/download"
        },
        {
            "id": "TarjInvers",
            "description": "Buscá una tarjeta igual a esta y apuntale con la cámara. (imgen de lo que tiene que buscar)",
            "objects": [
                {
                    "id": "ImgOk",
                    "position": "0 0 0",
                    "rotation": "0 0 0",
                    "scale": "1 1 1",
                    "type": "a-image",
                    "onclick": "drawText(¡Lo lograste! El código es ANismanLoMataron. Usalo para abrir el candado.)",
                    "media": "/media/Morzat/ImgErr/ok.png",
                    "marker": "hiro"
                },
                {
                    "id": "ImgErr",
                    "position": "1.232 0.16617 0.09778",
                    "rotation": "0 0 0",
                    "scale": "1 1 1",
                    "type": "a-image",
                    "onclick": "goTo(RetryInver)",
                    "media": "/media/Morzat/ImgErr/err.jpg",
                    "marker": "hiro"
                }
            ]
        },
        {
            "id": "RetryInver",
            "description": "Estás cerca. Volvé a intentarlo.",
            "next": 6
        }
    ]
}

**Comment by agusalex** [comment]
Problem is calling onClick() without "" closing now
